name: Pylint

on: [push]

jobs:
  build:
    # Run on Ubuntu 20.04
    runs-on: ubuntu-20.04  #ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # 3.10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install the p4Utils dependency from github with curl and bash
      run: |
        curl -sSL https://raw.githubusercontent.com/nsg-ethz/p4-utils/master/install-tools/install-p4-dev.sh | bash
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
        pylint $(git ls-files 'controllers/*.py')
