name: Pylint

on: [push]

jobs:
  build:
    # Run on Ubuntu 20.04
    runs-on: ubuntu-20.04  #ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # 3.10
    steps:
    # Étape 1 : Vérifier le code source
    - uses: actions/checkout@v4
    # Étape 2 : Installer GCC 9.4
    - name: Install GCC 9.4
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60
        gcc --version
    # Étape 3 : Installer Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # Étape 4 : Installer les dépendances Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    # Étape 5 : Installer les dépendances P4Utils
    - name: Install the p4Utils dependency from github with curl and bash
      run: |
        sudo apt-get install -y thrift-compiler
        sudo apt-get install -y libthrift-dev
        curl -sSL https://raw.githubusercontent.com/nsg-ethz/p4-utils/master/install-tools/install-p4-dev.sh | bash
    # Étape 6 : Lancer le linter pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
